services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=enthusiast
      - POSTGRES_PASSWORD=enthusiast
      - POSTGRES_DB=enthusiast
  redis:
    image: redis:latest
  frontend:
    image: upsidelab/enthusiast-frontend:latest
    environment:
      - PORT=10001
      - VITE_API_BASE=http://localhost:10000
      - VITE_WS_BASE=ws://localhost:10000
    ports:
      - "10001:10001"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - ./config/env
    environment:
      - PORT=10000
      - RUN_MIGRATIONS=True
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/env
    environment:
      - RUN_MIGRATIONS=False
      - RUN_WORKER=True
